name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  macos_build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - name: Write local.bazelrc File
      shell: bash
      run: |
        cat >local.bazelrc <<EOF
        common --config=ci
        EOF

    - name: Output the Bazel Info
      shell: bash
      run: |
        bazelisk info

    - name: Execute Tests
      shell: bash
      run: |
        bazelisk test //... 

    - name: Build Anything Not Tested
      shell: bash
      run: |
        bazelisk build //... 

    - name: Test Simple Example - No Changes
      shell: bash
      run: |
        cd examples/simple
        bazelisk test //...

    - name: Test Simple Example With Build File Changes
      shell: bash
      run: |
        cd examples/simple
        # Change t
        cp mockascript/internal/BUILD.bazel mockascript/internal/BUILD.bazel.orig
        echo "load(':foo.bzl', 'foo')" >> mockascript/internal/BUILD.bazel

